In [1]:
import numpy as np
import time

# Create large data
size = 100000
python_list = list(range(size))
numpy_array = np.arange(size)

# -------- Python List --------
start = time.time()
result_list = [x + 15 for x in python_list]
end = time.time()

print("Python List Time:", end - start)

# -------- NumPy Array --------
start = time.time()
result_numpy = numpy_array + 15
end = time.time()

print("NumPy Time:", end - start)

Python List Time: 0.004626750946044922
NumPy Time: 0.0002987384796142578


In [4]:
import numpy as np

arr = np.array(([1, 2, 3, 4, 5],[9,8,6,7,77],[11,22,33,44,55],[99,88,778,66,444],[8,5,4,9,6]))


print(arr)

print(type(arr))
arr.ndim
arr.shape
arr.size
arr.dtype
print("The dimention of array is :" ,arr.ndim)
print("The shape of array is :",arr.shape)
print("The total size of array is :",arr.size)
print("The dtype of array is :",arr.dtype )
#finding index 
#arr[3][2]
#array
# arr.max()
# arr.min()
# arr.argmax() show index of max number
#arr.argmin() show index of min number
arr.reshape
print(arr)


[[  1   2   3   4   5]
 [  9   8   6   7  77]
 [ 11  22  33  44  55]
 [ 99  88 778  66 444]
 [  8   5   4   9   6]]
<class 'numpy.ndarray'>
The dimention of array is : 2
The shape of array is : (5, 5)
The total size of array is : 25
The dtype of array is : int64
[[  1   2   3   4   5]
 [  9   8   6   7  77]
 [ 11  22  33  44  55]
 [ 99  88 778  66 444]
 [  8   5   4   9   6]]


In [51]:
arr

array([[  1,   2,   3,   4,   5],
       [  9,   8,   6,   7,  77],
       [ 11,  22,  33,  44,  55],
       [ 99,  88, 778,  66, 444],
       [  8,   5,   4,   9,   6]])

In [6]:
import numpy as np
arr = np.array(3233)
print(arr)

3233


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [3]:

arr = np.array([[[1, 2, 3], [4, 5, 6],[66,77,88]], [[1, 2, 3], [4, 5, 6],[22,33,44]]])

print(arr)
#
arr[1][2][-2]
arr.shape
arr.dtype
arr.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [66 77 88]]

 [[ 1  2  3]
  [ 4  5  6]
  [22 33 44]]]


3

In [7]:
arr = np.array([1,2,3,4,5,67])
print(arr)

[ 1  2  3  4  5 67]


In [12]:
print(arr[1:3])
print(arr[3:6])
print(arr[1:])
print(arr[:-1])
arr.dtype
arr.ndim

[2 3]
[ 4  5 67]
[ 2  3  4  5 67  8]
[ 1  2  3  4  5 67]


1

In [13]:
a= np.array([[1,2,3,4,5],[9,87,65,44,33]])
print(a)
a.ndim

[[ 1  2  3  4  5]
 [ 9 87 65 44 33]]


2

In [14]:
print(a[1:,2:])

[[65 44 33]]


In [10]:
arr.reshape
print(arr)
reshape =arr.reshape(2,3)
print(reshape)

[ 1  2  3  4  5 67]
[[ 1  2  3]
 [ 4  5 67]]


In [25]:
arr.flatten

<function ndarray.flatten(order='C')>

In [27]:
arr[1]

np.int64(2)

In [28]:
arr.size

7

In [29]:
arr.shape

(7,)

In [31]:
arr.sort

<function ndarray.sort(axis=-1, kind=None, order=None, *, stable=None)>

In [33]:
arr.sort
print(arr)

[ 1  2  3  4  5 67  8]


In [ ]:
h =np.array([[12,34,55,66,77,44],[1,34,5,6,7,74],[22,55,1,88,77,55],[55,44,33,22,11,88]])
print(h)
h

[[12 34 55 66 77 44]
 [ 1 34  5  6  7 74]
 [22 55  1 88 77 55]
 [55 44 33 22 11 88]]
