In [2]:
import numpy as np


In [12]:
a=np.array([2, 3, 4])
b=np.array([5, 6, 7])
d= a * b
print(d)
d.dtype
d.ndim

[10 18 28]


1

In [14]:
import numpy as np
d= np.arange(10)
print(d)
g= np.arange(2, 10, dtype=float)
print(g)
e= np.arange(2, 3, 0.1)
print(e)

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [19]:
f= np.linspace(1, 4, 6)
print(f)

[1.  1.6 2.2 2.8 3.4 4. ]


In [21]:
r=np.arange(1,5)

In [22]:
r

array([1, 2, 3, 4])

In [25]:
m=np.eye(4)
print(m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
mat=np.eye(4,k=2)
print(mat)
mat1=np.eye(4,k=-1)
print(mat1)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [34]:
a = np.array([1,2,3])
np.sqrt(a)
#np.exp(a)
#np.sin(a)
#np.log(a)
#np.max(a)

array([1.        , 1.41421356, 1.73205081])

In [36]:
a = np.array([1,2,3])
a.astype(float)
np.array([1.5,2.6]).astype(int)
np.array(['1','2']).astype(int)
np.array([True,False]).astype(int)
#np.array([1,2,3], dtype='float32')

array([1, 0])

In [42]:
a = np.array([1,2,3])
a + 5
a * 2
#np.ones((3,3)) + np.array([1,2,3])
#np.arange(3).reshape(3,1) + np.arange(3)
#a - 1

array([2, 4, 6])

In [56]:
x=np.arange(20)
print(x)
x3d = x.reshape(5, 2, 2)
print(x3d)
x3d.ndim
x3d.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


(5, 2, 2)

In [50]:
a = np.array([[1, 2], [3, 4]])   
b = np.array([[5, 6], [7, 8]])   

c0 = np.concatenate((a, b), axis=0)
print(c0)
c1 = np.concatenate((a, b), axis=1)
print(c1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
# np.random.rand(3)
# np.random.rand(2,2)
# np.random.randint(1,10,5)
a= np.random.rand (3)
print(a.astype(int))

[0 0 0]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
# np.save('array.npy', arr)
# np.load('array.npy')
# np.savetxt('array.txt', arr)
# np.loadtxt('array.txt')
# np.savez('multiple_array.npz', a=a, b=b)

In [16]:
arr[arr>3]
#arr[arr%2==0]
#arr[(arr>2)&(arr<6)]
#arr[arr!=3]
# arr[arr==5]
#arr.ndim

array([4, 5, 6])

In [21]:
s= np.zeros((2,3))
print(s.astype (bool))
d= np.ones((3,3))
print(d.astype(bool))

[[False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#np.arange(0,10,2)
a = np.array([1,2,3])
np.sqrt(a)
np.exp(a)
np.sin(a)
np.log(a)
np.max(a)

array([0.        , 0.69314718, 1.09861229])