In [60]:
import numpy as np


In [61]:
x= np.array([[1,2,3,4,5],[11,22,33,44,55],[9,8,7,6,5],[99,88,77,66,55]])
print(x)

[[ 1  2  3  4  5]
 [11 22 33 44 55]
 [ 9  8  7  6  5]
 [99 88 77 66 55]]


In [62]:
x.ndim
x.dtype
x.argmax()
x.argmin()
x.max
x.min
x.size
x.flatten()
x.reshape(5,4)
print("Dimention of array is :", x.ndim)
print("dtype of array is :", x.dtype)
print("max number index is :" ,x.argmax())
print("Min number inder is :", x.argmin())
print("max number of array is:",x.max())
print("min number of array is :",x.min())
print("the size of array is :",x.size)
print("changing array in 1D",x.flatten())
print("After reshaping the new array is ")
print(x.reshape(5,4))



Dimention of array is : 2
dtype of array is : int64
max number index is : 15
Min number inder is : 0
max number of array is: 99
min number of array is : 1
the size of array is : 20
changing array in 1D [ 1  2  3  4  5 11 22 33 44 55  9  8  7  6  5 99 88 77 66 55]
After reshaping the new array is 
[[ 1  2  3  4]
 [ 5 11 22 33]
 [44 55  9  8]
 [ 7  6  5 99]
 [88 77 66 55]]


In [63]:
np.mean(x)
np.median(x)
print("mean of array is :",np.mean(x))
print("median of array is :",np.median(x))

mean of array is : 30.0
median of array is : 10.0


In [64]:
import numpy as np
from scipy import stats
mode = stats.mode(x)
print("mode of array is :",mode)

mode of array is : ModeResult(mode=array([1, 2, 3, 4, 5]), count=array([1, 1, 1, 1, 2]))


# PANDAS


In [ ]:
import pandas as pd


In [ ]:
show = {
  'cars': ["BMW", "Volvo", "Ford","mercerdes","Bugatti chiron","Rolls Royes"],
  'passings': [3, 7, 2, 3, 5,9]
}

myvar = pd.DataFrame(show)

print(myvar)
print(type(show))

             cars  passings
0             BMW         3
1           Volvo         7
2            Ford         2
3       mercerdes         3
4  Bugatti chiron         5
5     Rolls Royes         9
<class 'dict'>


In [ ]:
m = pd.DataFrame([
    {'Name': 'Ahmad', 'Age': 25, 'City': 'Lahore'},
    {'Name': 'Bilal', 'Age': 22, 'City': 'karachi'},
    {'Name': 'Hamza', 'Age': 21, 'City': 'Islamabad'},
    {'Name': 'Hassan', 'Age': 23, 'City': 'Peshawar'},
    {'Name': 'Amjad', 'Age': 27, 'City': 'Multan'},
    {'Name': 'Shah', 'Age': 28, 'City': 'Pindi'},
    {'Name': 'Ali', 'Age': 31, 'City': 'Bhatti Bhangu'},
    {'Name': 'Khan', 'Age': 33, 'City': 'Mardan'},
    {'Name': 'Anwar', 'Age': 34, 'City': 'Gujrat'},
    {'Name': 'Tariq', 'Age': 55, 'City': 'Sialkot'},
    {'Name': 'Nawaz', 'Age': 45, 'City': 'Gujranwala'},
    {'Name': 'Shabzada', 'Age': 20, 'City': 'Wazirabad'},
    
])
print(m)
print("--------------------")
m.sort_values("Age")
m.sort_values("Name")
print(m.sort_values("Age"))
print("--------------------")
print(m.sort_values("Name"))
print("--------------------")

        Name  Age           City
0      Ahmad   25         Lahore
1      Bilal   22        karachi
2      Hamza   21      Islamabad
3     Hassan   23       Peshawar
4      Amjad   27         Multan
5       Shah   28          Pindi
6        Ali   31  Bhatti Bhangu
7       Khan   33         Mardan
8      Anwar   34         Gujrat
9      Tariq   55        Sialkot
10     Nawaz   45     Gujranwala
11  Shabzada   20      Wazirabad
--------------------
        Name  Age           City
11  Shabzada   20      Wazirabad
2      Hamza   21      Islamabad
1      Bilal   22        karachi
3     Hassan   23       Peshawar
0      Ahmad   25         Lahore
4      Amjad   27         Multan
5       Shah   28          Pindi
6        Ali   31  Bhatti Bhangu
7       Khan   33         Mardan
8      Anwar   34         Gujrat
10     Nawaz   45     Gujranwala
9      Tariq   55        Sialkot
--------------------
        Name  Age           City
0      Ahmad   25         Lahore
6        Ali   31  Bhatti Bhangu
4

In [ ]:
df3 = pd.DataFrame(np.random.randn(4, 3), 
                   columns=['A', 'B', 'C'],
                   index=['Row1', 'Row2', 'Row3', 'Row4'])
print(df3)

             A         B         C
Row1 -0.507400  1.765316  1.338032
Row2 -0.252208 -0.172686 -0.221261
Row3  2.657678  0.622445 -0.573369
Row4 -0.737499  1.407011  0.530204


In [ ]:
#print(m.shape)
#print(m.info())
#print(m.describe())
#print(m["Name"])
#print(m[['Name', 'Age']])
#print(m.iloc[0])
#print(m.loc[0]) 
#print(m.iloc[1:9])
#print(m[m['Age'] > 28])
print(m.head(9))
print(m.tail(9))

     Name  Age           City
0   Ahmad   25         Lahore
1   Bilal   22        karachi
2   Hamza   21      Islamabad
3  Hassan   23       Peshawar
4   Amjad   27         Multan
5    Shah   28          Pindi
6     Ali   31  Bhatti Bhangu
7    Khan   33         Mardan
8   Anwar   34         Gujrat
        Name  Age           City
3     Hassan   23       Peshawar
4      Amjad   27         Multan
5       Shah   28          Pindi
6        Ali   31  Bhatti Bhangu
7       Khan   33         Mardan
8      Anwar   34         Gujrat
9      Tariq   55        Sialkot
10     Nawaz   45     Gujranwala
11  Shabzada   20      Wazirabad


In [ ]:
#print(m['Age'].unique())
print(m['Name'].nunique())

12


In [ ]:
df_null = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5, np.nan],
    'B': [np.nan, 2, 3, np.nan, 5, 9],
    'C': [1, 2, 3, 4, 5, np.nan]
})

# Check for nulls
print(df_null.isnull())
print("---------------------")
print(df_null.isnull().sum())
print("---------------------")
print(df_null.isnull().sum().sum())
print("---------------------")
# Check for non-nulls
print(df_null.notnull())
print("---------------------")
print(df_null.notnull().sum())
print("---------------------")

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False   True  False
4  False  False  False
5   True  False   True
---------------------
A    2
B    2
C    1
dtype: int64
---------------------
5
---------------------
       A      B      C
0   True  False   True
1   True   True   True
2  False   True   True
3   True  False   True
4   True   True   True
5  False   True  False
---------------------
A    4
B    4
C    5
dtype: int64
---------------------
